# Generated by Django 4.0.3 on 2022-04-02 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='another_invite',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\w{6}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_invite',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\w{6}$')]),
        ),
    ]
